"""initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-05-06
"""
from alembic import op
import sqlalchemy as sa

revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('detected_tokens', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(255), nullable=False), sa.Column('symbol', sa.String(50), nullable=False), sa.Column('contract_address', sa.String(255), nullable=False), sa.Column('chain', sa.String(10), nullable=False), sa.Column('market_cap', sa.Float()), sa.Column('liquidity', sa.Float()), sa.Column('price_usd', sa.Float()), sa.Column('price_native', sa.Float()), sa.Column('volume_24h', sa.Float()), sa.Column('price_change_24h', sa.Float()), sa.Column('holders', sa.Integer()), sa.Column('buy_tax', sa.Float()), sa.Column('sell_tax', sa.Float()), sa.Column('dextools_url', sa.Text()), sa.Column('dex_pair_url', sa.Text()), sa.Column('deployer_wallet', sa.String(255)), sa.Column('social_links', sa.Text()), sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint('contract_address', 'chain'))
    op.create_table('open_positions', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('token_symbol', sa.String(50), nullable=False), sa.Column('chain', sa.String(10), nullable=False), sa.Column('entry_price', sa.Float(), nullable=False), sa.Column('tokens_received', sa.Float(), nullable=False), sa.Column('buy_amount_native', sa.Float(), nullable=False), sa.Column('buy_tx_hash', sa.String(255), nullable=False), sa.Column('pair_address', sa.String(255)), sa.Column('peak_price', sa.Float(), default=0), sa.Column('trailing_activated', sa.Integer(), default=0), sa.Column('entry_liquidity', sa.Float(), default=0), sa.Column('user_id', sa.BigInteger(), default=0), sa.Column('tiers_completed', sa.Text(), default='[]'), sa.Column('tp1_hit', sa.Boolean(), default=False), sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint('token_address', 'chain', 'user_id'))
    op.create_table('completed_trades', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('token_symbol', sa.String(50), nullable=False), sa.Column('chain', sa.String(10), nullable=False), sa.Column('entry_price', sa.Float(), nullable=False), sa.Column('exit_price', sa.Float(), nullable=False), sa.Column('tokens_amount', sa.Float(), nullable=False), sa.Column('buy_amount_native', sa.Float(), nullable=False), sa.Column('sell_amount_native', sa.Float(), nullable=False), sa.Column('profit_usd', sa.Float()), sa.Column('roi_percent', sa.Float(), nullable=False), sa.Column('buy_tx_hash', sa.String(255), nullable=False), sa.Column('sell_tx_hash', sa.String(255), nullable=False), sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False), sa.Column('closed_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('duration_seconds', sa.Integer()), sa.Column('user_id', sa.BigInteger(), default=0), sa.Column('close_reason', sa.String(20)))
    op.create_table('allowed_users', sa.Column('user_id', sa.BigInteger(), primary_key=True), sa.Column('username', sa.String(255)), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('user_wallets', sa.Column('user_id', sa.BigInteger(), primary_key=True), sa.Column('public_key', sa.String(255), nullable=False), sa.Column('encrypted_private_key', sa.Text(), nullable=False), sa.Column('encrypted_seed_phrase', sa.Text(), default=''), sa.Column('auto_trade', sa.Integer(), default=1), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('user_settings', sa.Column('user_id', sa.BigInteger(), primary_key=True), sa.Column('min_score', sa.Integer()), sa.Column('stop_loss', sa.Integer()), sa.Column('take_profit', sa.Integer()), sa.Column('buy_percent', sa.Integer()), sa.Column('trailing_drop', sa.Integer()), sa.Column('slippage', sa.Integer()), sa.Column('max_positions', sa.Integer()), sa.Column('max_buy_amount', sa.Float()), sa.Column('compound_enabled', sa.Integer()), sa.Column('compound_percent', sa.Integer()), sa.Column('tp1_percent', sa.Float()), sa.Column('tp1_sell_percent', sa.Float()), sa.Column('tp2_percent', sa.Float()), sa.Column('trailing_sl_percent', sa.Float()), sa.Column('daily_loss_limit_percent', sa.Float()), sa.Column('capital_per_trade', sa.String(50)), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('token_blacklist', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('chain', sa.String(10), default='SOL'), sa.Column('reason', sa.Text(), default=''), sa.Column('added_by', sa.BigInteger(), nullable=False), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint('token_address', 'chain', 'added_by'))
    op.create_table('token_whitelist', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('chain', sa.String(10), default='SOL'), sa.Column('label', sa.Text(), default=''), sa.Column('added_by', sa.BigInteger(), nullable=False), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint('token_address', 'chain'))
    op.create_table('whale_wallets', sa.Column('address', sa.String(255), primary_key=True), sa.Column('label', sa.Text(), default=''), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('whale_events', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('wallet_address', sa.String(255), nullable=False), sa.Column('token_mint', sa.String(255), nullable=False), sa.Column('token_symbol', sa.String(50), default=''), sa.Column('sol_spent', sa.Float(), nullable=False), sa.Column('tokens_received', sa.Float(), nullable=False), sa.Column('tx_signature', sa.String(255), nullable=False, unique=True), sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('bot_chats', sa.Column('chat_id', sa.BigInteger(), primary_key=True), sa.Column('chat_type', sa.String(20), default='private'), sa.Column('title', sa.String(255), default=''), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('scan_history', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('contract_address', sa.String(255), nullable=False), sa.Column('chain', sa.String(10), nullable=False), sa.Column('symbol', sa.String(50), nullable=False), sa.Column('name', sa.String(255), nullable=False), sa.Column('score', sa.Integer(), nullable=False), sa.Column('score_breakdown', sa.Text()), sa.Column('market_cap', sa.Float()), sa.Column('liquidity', sa.Float()), sa.Column('volume_24h', sa.Float()), sa.Column('price_usd', sa.Float()), sa.Column('holders', sa.Integer()), sa.Column('buy_tax', sa.Float()), sa.Column('sell_tax', sa.Float()), sa.Column('source', sa.String(50), default=''), sa.Column('was_bought', sa.Integer(), default=0), sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('snipe_targets', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('user_id', sa.BigInteger(), nullable=False), sa.Column('amount', sa.Float(), default=0), sa.Column('status', sa.String(20), default='active'), sa.Column('buy_tx_hash', sa.String(255), default=''), sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('filled_at', sa.DateTime(timezone=True)), sa.UniqueConstraint('token_address', 'user_id'))
    op.create_table('fee_ledger', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.BigInteger(), nullable=False), sa.Column('token_symbol', sa.String(50), nullable=False), sa.Column('trade_profit_native', sa.Float(), nullable=False), sa.Column('fee_amount_native', sa.Float(), nullable=False), sa.Column('fee_percent', sa.Float(), nullable=False), sa.Column('fee_tx_hash', sa.String(255)), sa.Column('status', sa.String(20), default='pending'), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('dca_orders', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.BigInteger(), nullable=False), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('token_symbol', sa.String(50), default=''), sa.Column('chain', sa.String(10), default='SOL'), sa.Column('total_amount', sa.Float(), nullable=False), sa.Column('amount_per_buy', sa.Float(), nullable=False), sa.Column('splits_total', sa.Integer(), nullable=False), sa.Column('splits_done', sa.Integer(), default=0), sa.Column('interval_seconds', sa.Integer(), nullable=False), sa.Column('status', sa.String(20), default='active'), sa.Column('last_buy_at', sa.DateTime(timezone=True)), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index('idx_dca_active_unique', 'dca_orders', ['user_id', 'token_address', 'chain'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('limit_orders', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.BigInteger(), nullable=False), sa.Column('token_address', sa.String(255), nullable=False), sa.Column('token_symbol', sa.String(50), default=''), sa.Column('chain', sa.String(10), default='SOL'), sa.Column('side', sa.String(10), nullable=False), sa.Column('amount', sa.Float(), nullable=False), sa.Column('target_price', sa.Float(), nullable=False), sa.Column('condition', sa.String(10), default='lte'), sa.Column('status', sa.String(20), default='active'), sa.Column('fill_tx_hash', sa.String(255), default=''), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('filled_at', sa.DateTime(timezone=True)))
    op.create_table('compound_fund', sa.Column('user_id', sa.BigInteger(), primary_key=True), sa.Column('available', sa.Float(), default=0.0), sa.Column('total_compounded', sa.Float(), default=0.0), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('daily_loss_records', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('user_id', sa.BigInteger(), nullable=False), sa.Column('date', sa.String(10), nullable=False), sa.Column('total_loss', sa.Float(), default=0.0), sa.Column('kill_switch_active', sa.Boolean(), default=False), sa.UniqueConstraint('user_id', 'date'))


def downgrade() -> None:
    for table in ['daily_loss_records', 'compound_fund', 'limit_orders', 'dca_orders', 'fee_ledger', 'snipe_targets', 'scan_history', 'bot_chats', 'whale_events', 'whale_wallets', 'token_whitelist', 'token_blacklist', 'user_settings', 'user_wallets', 'allowed_users', 'completed_trades', 'open_positions', 'detected_tokens']:
        op.drop_table(table)
